### ISSUE TITLE
How do I make a call to my actor methods? How do I mock things like the caller object available on public methods?

### ISSUE THREAD

**Issue by saikatdas0790** [kritzcreek/motoko-matchers#10]
Any examples would be really appreciated. Having gone through the docs, I don't believe it's possible. Please correct me if my understanding is wrong

**Comment by ByronBecker** [comment]
@saikatdas0790 Have you tried this pattern https://kritzcreek.github.io/motoko-matchers/Canister.html?

**Comment by saikatdas0790** [comment]
> @saikatdas0790 Have you tried this pattern https://kritzcreek.github.io/motoko-matchers/Canister.html?

I'll try and get back if issues
