### ISSUE TITLE
Upgrade to latest Motoko compiler + Motoko base

### ISSUE THREAD

**Issue by tiagol89** [kritzcreek/motoko-matchers#11]
Hi @kritzcreek ,

This lib is widely used for testing on the IC, but to my surprise it hasn't been updated for 2 years.

I have forked this project and will be updating on it to the latest compiler + motoko base. 
I can easily create a PR that updates this repo too, would you be interested / accept it?

Thank you,
Tiago

**Comment by kritzcreek** [comment]
Fixed in #13 

I've also added some commits to master to update versions in CI and apply VSCode's formatting to all files.

After merging https://github.com/kritzcreek/motoko-matchers/pull/15 I'll make a new release.

**Comment by kritzcreek** [comment]
Released as v1.3.0
