### ISSUE TITLE
Fix broken link in package-set for `v1.2.0`

### ISSUE THREAD

**Issue by rvanasa** [kritzcreek/motoko-matchers#16]
Hello! I received a bug report that is apparently caused by `matchers v1.2.0` referencing `kritzkreek/vessel-package-set` instead of `dfinity/vessel-package-set` in the `v1.2.0` package-set file. 

Because several libraries include this version of `matchers` as a transitive dependency (which is then picked up by the [Mops](https://mops.one/) package manager), would it be possible to patch the `package-set.dhall` file in the `v1.2.0` tag as a quick fix for this recurring situation? Thanks!

**Comment by kritzcreek** [comment]
Hello! Referencing `kritzkreek/vessel-package-set` should be just fine, as Github sets up redirects for moved repositories and so the dhall expression evaluates fine. Additionally the `package-set.dhall` or `vessel.dhall` files in here aren't part of the interface or metadata of the package. I don't understand why Mops would have a problem here.

If someone can explain to me what's going on, I can update the Url, but I won't modify released tags. I'll make a new patch release instead.

**Comment by Gwojda** [comment]
Hi, 
Any news on this ? Facing the same issue, look like we should use dfinity/vessel-package-set instead of kritzkreek/vessel-package-set in 1.2.0 like @rvanasa said.
@rvanasa Did you found an solution ? Actually we can t update to 1.3.0 because of migration problems we can't solve in short term.
Thanks !

**Comment by rvanasa** [comment]
It might be possible to work around this by forking this repository, fixing the broken link, and then manually specifying the version of Matchers as the forked repo URL in the `mops.toml` file. That's unfortunately about all we can do without this being changed in the official repository.

**Comment by kritzcreek** [comment]
This "issue" has long been fixed in v1.3.0 (which isn't breaking from v1.2.0 so should be easy to update).
