### ISSUE TITLE
Local testing

### ISSUE THREAD

**Issue by xenide** [kritzcreek/motoko-matchers#7]
May I know how do you intend for the tests to be run locally? There is no supported `dfx` command for that, right?

**Comment by kritzcreek** [comment]
I'd recommend checking out https://github.com/kritzcreek/motoko-library-template and how I've set up testing there.

TLDR: You can use `wasmtime` (as long as you don't use any features that are excluse to the IC)

**Comment by xenide** [comment]
Understood, thanks for replying. But this is the best testing solution / framework you know of right, in the scope of ICP?

**Comment by kritzcreek** [comment]
@xenide There's the `Canister` module in matchers here, which works for small-ish tests.
https://github.com/kritzcreek/motoko-matchers/blob/cb838c192df3328ff9ae172e2dc7338cf55e74bf/src/Canister.mo#L16-L49

For a more scalable approach, I'd check out `CanCan`: https://github.com/dfinity/cancan/tree/main/service/tests. They're using a tool called `ic-repl` IIRC, which makes it easy to script some tests with candid and bash.

And finally you can always use an E2E testing solution and drive your tests through the browser with something like Selenium.

That's all the options I know of for now, but now is the best time for you/the community to come up with a better approach for all of us ;)
